<?php

namespace Container7NviUxy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8MK8MbPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8MK8MbP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8MK8MbP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.283mTwu', NULL, 'Cannot determine controller argument for "App\\Controller\\PageController::ficha()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
        ]);
    }
}
