<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJIRWLnx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJIRWLnx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJIRWLnx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJIRWLnx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJIRWLnx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JIRWLnx',
    'container.build_id' => '18b3d7b3',
    'container.build_time' => 1727172313,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJIRWLnx');
