<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjNWmo8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjNWmo8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjNWmo8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjNWmo8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXjNWmo8\App_KernelDevDebugContainer([
    'container.build_hash' => 'XjNWmo8',
    'container.build_id' => 'e1a2bcad',
    'container.build_time' => 1727335034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjNWmo8');
